services:
  nginx:
    image: nginx:alpine
    container_name: teste-nginx-lb
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
    restart: unless-stopped
    networks:
      - backend
      - payment-processor

  api1:
    image: ruanpcr/rinha-api:latest
    container_name: teste-r-api-1
    platform: linux/amd64
    command: ["/app/wait-for-redis.sh"]
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "105MB"
    restart: unless-stopped
    networks:
      - backend
      - payment-processor

  api2:
    image: ruanpcr/rinha-api:latest
    container_name: teste-r-api-2
    platform: linux/amd64
    command: ["/app/wait-for-redis.sh"]
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "105MB"
    restart: unless-stopped
    networks:
      - backend
      - payment-processor

  redis:
    image: redis:7-alpine
    container_name: teste-redis
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
    restart: unless-stopped
    networks:
      - backend

  worker:
    image: ruanpcr/rinha-worker:latest
    container_name: teste-worker
    platform: linux/amd64
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"
    restart: unless-stopped
    networks:
      - backend
      - payment-processor

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
