services:
  load-balance:
    image: lpj145/rinha-lb:1.10
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    networks:
      - backend
      - payment-processor
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
    ports:
      - 9999:9999
    volumes:
    - ./dev/shm:/var/run/sockets
    environment:
      - SOCKET_DIR=/var/run/sockets
    depends_on:
      - api1
      - api2
    cpuset: "0,1,2,3"
    cpus: "1.3"
    mem_limit: "45MB"

  api1: &api
    image: lpj145/rinha-lb:1.10
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    hostname: api1
    environment:
      - SOCKET_DIR=/var/run/sockets
      - MODE=worker
    volumes:
      - ./dev/shm:/var/run/sockets
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "150MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - MODE=worker
      - SOCKET_DIR=/var/run/sockets
      - HOST=api2
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
